# Generated by Django 5.2.17 on 2026-10-02 03:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('initials', models.CharField(default='', max_length=8)),
                ('role', models.CharField(choices=[('safety_manager', 'Safety Manager'), ('investigator', 'Investigator'), ('safety_officer', 'Safety Officer'), ('auditor', 'Auditor'), ('admin', 'Administrator')], default='safety_officer', max_length=32)),
                ('title', models.CharField(default='', max_length=120)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('base', models.CharField(default='DEL — HQ', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('license_number', models.CharField(blank=True, max_length=60, null=True)),
                ('avatar_tone', models.CharField(choices=[('brand', 'brand'), ('violet', 'violet'), ('amber', 'amber'), ('teal', 'teal'), ('rose', 'rose')], default='brand', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alias_emails', models.JSONField(blank=True, default=list)),
                ('organisation', models.CharField(default='SkyShield Operations', max_length=160)),
                ('email_verified', models.BooleanField(default=False)),
                ('failed_count', models.IntegerField(default=0)),
                ('failed_first_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('token', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=120)),
                ('org', models.CharField(default='SkyShield Operations', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
