# Generated by Django 5.2.17 on 2026-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='attachments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='file',
            field=models.FileField(blank=True, max_length=240, null=True, upload_to='evidence/'),
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=80)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=240)),
                ('status_code', models.IntegerField()),
                ('content_type', models.CharField(default='application/json', max_length=120)),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session_key', 'key', 'method', 'path'), name='uniq_idempotency_scope')],
            },
        ),
    ]
